version: '3.10'
services:
  mysql:
    image: mysql:8.0.27
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

    ports:
      - '5432:5432'

    volumes:
      - ./data_postgres:/var/lib/postgresql

  node-app:
      build: ./gate-simulator
      image: node-app:Dockerfile.0
      ports:
        - '9999:9999'

